#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Parallel boilerplate-exclusion checker (multi-kernel vLLM) with resume capability.

Example:
python 14_check_boilerplate.py \
  --model openai/gpt-oss-120b \
  --download_dir ../meta_ai \
  --gpus 0,1,2,3,4,5,6,7 \
  --gpus_per_kernel 2 \
  --prompt_batch_size 1000 \
  --max_model_len 30000 \
  --out_dir ./boilerplate_checks

Notes
- Each kernel runs in its own process and sees only its assigned GPUs via CUDA_VISIBLE_DEVICES.
- tensor_parallel_size == gpus_per_kernel.
- Input defaults to your six CSVs; override with flags if needed.
- RESUMABLE: If interrupted, re-run with same arguments to skip already-processed batches.
- Final outputs:
    {out_dir}/shards/worker{K}_part{P}_{start}_{end}.parquet
    {out_dir}/final_boilerplate_checks.parquet (and .csv)
"""

import argparse
import os
import sys
import math
import re
import warnings
from pathlib import Path
from typing import List, Tuple

import pandas as pd
import numpy as np
import multiprocessing as mp

# ----------------------------
# LLM utilities (import in worker to avoid forking CUDA)
# ----------------------------

def build_prompts(patient_boilerplates: List[str], trial_boilerplates: List[str], tokenizer) -> List[str]:
    prompts = []
    for p_blp, t_blp in zip(patient_boilerplates, trial_boilerplates):
        messages = [
            {'role': 'system', 'content': "Reasoning: high"},
            {'role': 'user', 'content': (
                "You are a brilliant oncologist with encyclopedic knowledge about cancer and its treatment.\n"
                "Your job is to evaluate whether a patient has any underlying medical conditions that would exclude him or her from a specific clinical trial.\n\n"
                f"Here is an extract of the patient's history:\n{p_blp}\n"
                f"Here are the exclusion criteria for the trial:\n{t_blp}\n"
                "Note that the extract was generated by prompting an LLM to determine whether the patient meets specific common exclusion criteria, "
                "such as uncontrolled brain metastases, lack of measurable disease, congestive heart failure, pneumonitis, renal dysfunction, "
                "liver dysfunction, and HIV or hepatitis infection, and to present evidence for whether the patient met the criterion.\n"
                "You should therefore not assume that mention of such condition means the patient has the condition; it may represent the LLM reasoning "
                "about whether the patient has the condition.\n"
                "Based on the extract, you should determine whether the patient clearly meets one of the exclusion criteria for this specific trial.\n"
                "Do not evaluate exclusion criteria other than those listed for this trial.\n"
                "Reason through one exclusion criterion at a time. Generate a numbered list of the criteria as you go. For each one, decide whether the patient clearly "
                "meets the exclusion criteron. If it is not completely clear that the patient meets the exclusion criterion, give the patient the benefit of the doubt, "
                "and err on the side of deciding the patient is not excluded. A description in the patient extract that a condition is mild, low-grade, or resolved is even "
                "more of a reason not to exclude the patient based on that condition.\n"
                'Once you have evaluated all exclusion criteria, answer the question "Is this patient clearly excluded from this trial?" with a one-word "Yes!" or "No!" answer, '
                "based on whether the patient clearly met any of the individual exclusion criteria. It is critical that your final word be either \"Yes!\" or \"No!\", verbatim, and case-sensitive.\n"
                "Make sure to include the exclamation point in your final one-word answer.\n"
                "No introductory text or concluding text after that final answer."
            )}
        ]
        prompt = tokenizer.apply_chat_template(conversation=messages, add_generation_prompt=True, tokenize=False, enable_thinking=True)
        prompts.append(prompt)
    return prompts


def parse_yes_no_at_end(text: str) -> int:
    #look near the end for one of the exact tokens
    tail = text[-10:].upper()
    if "YES!" in tail:
        return 1.0
    elif "NO!" in tail:
        return 0.0
    else:
        # fallback: simple heuristic
        return (1.0 if "YES" in tail else 0.0)



def ask_about_boilerplate_batch(patient_boilerplates, trial_boilerplates, llm, sampling_params):
    from vllm.reasoning.gemma4_utils import parse_thinking_output
    tokenizer = llm.get_tokenizer()
    prompts = build_prompts(patient_boilerplates, trial_boilerplates, tokenizer)
    responses = llm.generate(prompts, sampling_params)
    parsed = [parse_thinking_output(r.outputs[0].text) for r in responses]
    response_reasonings = [(p["thinking"] or "") for p in parsed]
    response_texts = [(p["answer"] or "") for p in parsed]
    exclusion_results = [parse_yes_no_at_end(t) for t in response_texts]
    return response_reasonings, response_texts, exclusion_results


# ----------------------------
# Data loading / sharding
# ----------------------------

def load_default_inputs(
    patients_rounds: List[str],
    trials_rounds: List[str]
) -> pd.DataFrame:
    frames = []
    for f in patients_rounds + trials_rounds:
        if not Path(f).exists():
            raise FileNotFoundError(f"Input file not found: {f}")
        frames.append(pd.read_parquet(f))
    df = pd.concat(frames, axis=0, ignore_index=True)
    return df


def prep_unique_pairs(df: pd.DataFrame) -> pd.DataFrame:
    # Filter like original
    df = df[~df.trial_boilerplate_text.isnull()]
    df = df[df.trial_boilerplate_text != ""]
    df = df[~df.patient_boilerplate_text.isnull()]
    df = df[df.patient_boilerplate_text != ""]
    # Unique combos (keep patient_summary to preserve input semantics)
    unique_df = (
        df.groupby(['patient_summary', 'nct_id', 'trial_boilerplate_text'])
          .first()
          .reset_index()[['nct_id', 'patient_summary', 'patient_boilerplate_text', 'trial_boilerplate_text']]
          .reset_index(drop=True)
    )
    # Attach a stable row_id to preserve original order later
    unique_df.insert(0, 'row_id', np.arange(len(unique_df), dtype=np.int64))
    return unique_df


def chunk_dataframe(df: pd.DataFrame, n_chunks: int) -> List[pd.DataFrame]:
    return list(np.array_split(df, n_chunks))


def group_gpus(gpu_list: List[int], gpus_per_kernel: int) -> List[List[int]]:
    n_groups = len(gpu_list) // gpus_per_kernel
    grouped = [gpu_list[i*gpus_per_kernel:(i+1)*gpus_per_kernel] for i in range(n_groups)]
    return grouped


# ----------------------------
# Worker process with resume capability
# ----------------------------

def worker_process(worker_id: int,
                   gpu_ids: List[int],
                   shard: pd.DataFrame,
                   args):
    import os
    os.environ["CUDA_VISIBLE_DEVICES"] = ",".join(str(i) for i in gpu_ids)
    # Optional: ensure FlashAttention if available
    # os.environ.setdefault("VLLM_ATTENTION_BACKEND", "FLASH_ATTN")
    # os.environ.setdefault("VLLM_USE_FLASHINFER_SAMPLER", "0")

    out_dir = Path(args.out_dir)
    (out_dir / "shards").mkdir(parents=True, exist_ok=True)

    print(f"[Worker {worker_id}] sees GPUs {gpu_ids} | shard size={len(shard)}", flush=True)

    # Process shard in prompt batches
    total = len(shard)
    batch_size = args.prompt_batch_size
    batches = math.ceil(total / batch_size)

    # First pass: check which batches are already completed
    batches_to_process = []
    existing_batches = []
    
    for b in range(batches):
        start = b * batch_size
        end = min((b + 1) * batch_size, total)
        batch = shard.iloc[start:end].copy()
        
        # Construct expected output path
        shard_path = out_dir / "shards" / f"worker{worker_id}_part{b}_{int(batch.row_id.min())}_{int(batch.row_id.max())}.parquet"
        
        if shard_path.exists():
            print(f"[Worker {worker_id}] Found existing batch {b} -> {shard_path.name} (SKIPPING)", flush=True)
            existing_batches.append(b)
        else:
            batches_to_process.append(b)
    
    print(f"[Worker {worker_id}] Found {len(existing_batches)} existing batches, will process {len(batches_to_process)} new batches", flush=True)
    
    # Only initialize LLM if there are batches to process
    if batches_to_process:
        from vllm import LLM, SamplingParams  # import here to avoid CUDA init in parent
        
        llm = LLM(
            model=args.model,
            tensor_parallel_size=args.gpus_per_kernel,
            download_dir=args.download_dir,
            gpu_memory_utilization=args.gpu_memory_utilization,
            max_num_seqs=args.max_num_seqs,
            max_model_len=args.max_model_len,
        )

        sampling_params = SamplingParams(
            temperature=0.0,
            top_k=1,
            max_tokens=args.max_new_tokens,
            repetition_penalty=1.1,
            skip_special_tokens=False,
        )

        # Process only the batches that don't exist yet
        for b in batches_to_process:
            start = b * batch_size
            end = min((b + 1) * batch_size, total)
            batch = shard.iloc[start:end].copy()

            p_blp = batch['patient_boilerplate_text'].tolist()
            t_blp = batch['trial_boilerplate_text'].tolist()

            try:
                resp_reasonings, resp_texts, excl = ask_about_boilerplate_batch(p_blp, t_blp, llm, sampling_params)
            except Exception as e:
                # Fail-safe: record error strings so we can debug later
                err = f"[Worker {worker_id}] ERROR batch {b}: {e}"
                print(err, flush=True)
                resp_reasonings = [""] * len(batch)
                resp_texts = [err] * len(batch)
                excl = [0] * len(batch)

            batch['boilerplate_check_llm_reasoning'] = resp_reasonings
            batch['boilerplate_check_llm_response'] = resp_texts
            batch['exclusion_result'] = excl

            # Write the shard
            shard_path = out_dir / "shards" / f"worker{worker_id}_part{b}_{int(batch.row_id.min())}_{int(batch.row_id.max())}.parquet"
            batch.to_parquet(shard_path, index=False)
            print(f"[Worker {worker_id}] wrote {len(batch)} rows -> {shard_path.name}", flush=True)
    else:
        print(f"[Worker {worker_id}] All batches already completed, no inference needed", flush=True)

    print(f"[Worker {worker_id}] DONE.", flush=True)


# ----------------------------
# Main
# ----------------------------

def parse_args():
    p = argparse.ArgumentParser(description="Parallel boilerplate exclusion checker (multi-kernel vLLM) with resume capability")

    # Model / runtime
    p.add_argument("--model", type=str, default="openai/gpt-oss-120b")
    p.add_argument("--download_dir", type=str, default="./meta_ai")
    p.add_argument("--max_model_len", type=int, default=30000)
    p.add_argument("--max_num_seqs", type=int, default=900, help="vLLM max_num_seqs (concurrent request cap).")
    p.add_argument("--max_new_tokens", type=int, default=25000)
    p.add_argument("--gpu_memory_utilization", type=float, default=0.97)

    # GPUs / kernels
    p.add_argument("--gpus", type=str, required=True, help="Comma-separated GPU ids, e.g., '0,1,2,3'")
    p.add_argument("--gpus_per_kernel", type=int, required=True, help="GPUs per vLLM kernel (tensor_parallel_size)")

    # Batching
    p.add_argument("--prompt_batch_size", type=int, default=512, help="Number of prompt pairs per generate() call")

    # IO
    p.add_argument("--out_dir", type=str, default="./boilerplate_checks")

    # Inputs (defaults to your six CSVs)
    p.add_argument("--patients_rounds", type=str,
                   default="../data/no_phi/top_cohorts_tocheck_round1.parquet,../data/no_phi/top_cohorts_tocheck_round2.parquet,../data/no_phi/top_cohorts_tocheck_round3.parquet",
                   help="Comma-separated CSVs of patient candidates")
    p.add_argument("--trials_rounds", type=str,
                   default="../data/no_phi/top_patients_tocheck_round1.parquet,../data/no_phi/top_patients_tocheck_round2.parquet,../data/no_phi/top_patients_tocheck_round3.parquet",
                   help="Comma-separated CSVs of trial candidates")

    return p.parse_args()


def main():
    args = parse_args()
    out_dir = Path(args.out_dir)
    (out_dir / "shards").mkdir(parents=True, exist_ok=True)

    # Resolve GPUs
    gpu_list = [int(x) for x in args.gpus.replace(" ", "").split(",") if x != ""]
    if args.gpus_per_kernel < 1:
        raise ValueError("--gpus_per_kernel must be >= 1")
    gpu_groups = group_gpus(gpu_list, args.gpus_per_kernel)
    if not gpu_groups:
        raise ValueError("Not enough GPUs for at least one kernel. "
                         f"Provided {len(gpu_list)}, need at least {args.gpus_per_kernel}.")
    if len(gpu_list) % args.gpus_per_kernel != 0:
        warnings.warn(f"GPU count {len(gpu_list)} not divisible by gpus_per_kernel {args.gpus_per_kernel}. "
                      f"Dropping {len(gpu_list) % args.gpus_per_kernel} GPU(s): {gpu_list[len(gpu_groups)*args.gpus_per_kernel:]}")

    # Load inputs and build unique combos
    patients_rounds = [s for s in args.patients_rounds.split(",") if s]
    trials_rounds = [s for s in args.trials_rounds.split(",") if s]

    print("[Main] Loading inputs...", flush=True)
    pc = load_default_inputs(patients_rounds, trials_rounds)
    unique_df = prep_unique_pairs(pc)
    print(f"[Main] Unique cohort combos: {len(unique_df)}", flush=True)

    # Check for existing final output
    final_parquet = out_dir / "final_boilerplate_checks.parquet"
    final_csv = out_dir / "final_boilerplate_checks.csv"
    
    if final_parquet.exists() and final_csv.exists():
        print(f"[Main] WARNING: Final output files already exist:", flush=True)
        print(f"  - {final_parquet}", flush=True)
        print(f"  - {final_csv}", flush=True)
        print(f"[Main] Individual shard processing will still resume from existing shards.", flush=True)

    # Shard dataframe across workers
    n_workers = len(gpu_groups)
    shards = chunk_dataframe(unique_df, n_workers)

    # Multiprocessing with 'spawn' to avoid CUDA fork issues
    mp.set_start_method("spawn", force=True)
    procs = []

    for wid, (gids, shard) in enumerate(zip(gpu_groups, shards)):
        if shard.empty:
            print(f"[Main] Worker {wid} got empty shard. Skipping.", flush=True)
            continue
        p = mp.Process(
            target=worker_process,
            args=(wid, gids, shard, args),
            daemon=False
        )
        p.start()
        procs.append(p)
        print(f"[Main] Launched worker {wid} on GPUs {gids} with {len(shard)} rows", flush=True)

    # Wait for workers
    for p in procs:
        p.join()
        if p.exitcode != 0:
            print(f"[Main] WARNING: worker exit code {p.exitcode}", flush=True)

    # Combine outputs in original order
    shard_files = sorted((out_dir / "shards").glob("worker*_part*.parquet"))
    if not shard_files:
        raise RuntimeError("No shard outputs found. Workers may have failed early.")

    print(f"[Main] Reading {len(shard_files)} shard files...", flush=True)
    parts = [pd.read_parquet(f) for f in shard_files]
    final = pd.concat(parts, axis=0, ignore_index=True)

    # Deduplicate (defensive) and sort by original row order
    final = final.sort_values("row_id").drop_duplicates(subset=["row_id"], keep="first").reset_index(drop=True)

    final.to_parquet(final_parquet, index=False)
    #final.to_csv(final_csv, index=False)
    print(f"[Main] Wrote {len(final)} rows -> {final_parquet} and {final_csv}", flush=True)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("Interrupted.", flush=True)
        sys.exit(130)
