#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
Per-document clinical note compression using vLLM server(s).

Each input row is treated as one independent clinical document and is
summarized into a concise oncology-focused paragraph. This mirrors the
"compress-notes" skill from the onc-data-wrangler plugin, but uses the same
local-vLLM server management pattern as 6_summarize_patients.py so that
multiple servers can be launched (own GPUs) or reused (external URLs).

Multiple vLLM servers can be launched in parallel to increase throughput.
The number of servers is determined by: n_servers = len(gpu_ids) // gpus_per_server.
Prompts are split into batches, and within each batch documents are distributed
across servers round-robin. After each batch completes its inference, a shard
file is written so that interrupted runs can be resumed.

The final output parquet preserves the original input columns and appends the
note-level compression outputs generated by this script.

Examples
--------
# Launch own servers, 1 GPU each on 8 GPUs:
python 3_compress_notes.py \
  --input_parquet ../data/no_phi/all_synthetic_notes.parquet \
  --output_parquet ../data/no_phi/compressed_notes.parquet \
  --shard_dir ../data/no_phi/compressed_note_shards \
  --model openai/gpt-oss-120b \
  --download_dir ~/models \
  --gpu_ids 0,1,2,3,4,5,6,7 \
  --gpus_per_server 1 \
  --max_model_len 25000 \
  --max_tokens 1024 \
  --patient_id_col pseudo_mrn \
  --text_col synthetic_note \
  --max_concurrent_requests 25

# Use existing external servers:
python 3_compress_notes.py \
  --input_parquet ../data/no_phi/all_synthetic_notes.parquet \
  --output_parquet ../data/no_phi/compressed_notes.parquet \
  --shard_dir ../data/no_phi/compressed_note_shards \
  --model openai/gpt-oss-120b \
  --download_dir ~/models \
  --server_urls http://localhost:8000/v1,http://localhost:8001/v1 \
  --max_model_len 25000 \
  --max_tokens 1024
"""

import argparse
import asyncio
import glob
import os
import re
import shlex
import subprocess
import sys
import warnings
from multiprocessing import Pool
from typing import List, Dict, Tuple, Optional, Any

import pandas as pd
import requests
from openai import AsyncOpenAI


# -------------------------
# Compression prompt
# -------------------------

COMPRESSION_SYSTEM_PROMPT = """\
You are an expert oncology clinical-document summarizer.

TASK:
Summarize one clinical document using only information explicitly stated in
the document and metadata supplied by the user.

OUTPUT FORMAT:
- Output only the summary text. Do not include headings, bullets, labels,
  markdown, preamble, caveats, or JSON.
- Use one paragraph of three sentences or less for the clinical document.
- If the document explicitly describes multiple independent primary cancers,
  output one paragraph per primary cancer diagnosis; each paragraph must still
  be three sentences or less.
- If a concept below is not mentioned in the document, omit that concept from
  the summary rather than writing that it is missing or unknown.
- Never write meta-commentary about the document itself. Do not state what the
  document does or does not contain, mention, address, describe, or discuss.
  Do not write phrases like "The document does not contain...", "No information
  is provided about...", "This report does not mention...", "The note focuses
  on...", or "This is not an oncology document." Just summarize the clinical
  content that is present.
- If the document has no oncology content (for example a spine imaging report
  for back pain, a non-cancer-related encounter, or an administrative note),
  simply summarize the clinical content that is present in three sentences or
  less. Do not add a disclaimer that the document is unrelated to cancer.

CONTENT TO CAPTURE WHEN PRESENT OR KNOWN:
- Age and sex.
- Cancer type and histology.
- Disease burden at diagnosis, including original stage, TNM, extent of
  metastatic disease, sites of involvement, and explicit disease risk scores
  such as International Prognostic Index, Follicular Lymphoma International
  Prognostic Index, or similar disease-specific scores.
- Current disease burden, including current sites of disease, progression,
  response, recurrence, remission, tumor markers such as carcinoembryonic
  antigen or CA 19-9, and clinically meaningful disease measurements.
- Biomarkers: capture all documented biomarkers without summarizing away
  individual results. Biomarkers include molecular alterations, cytogenetics,
  gene fusions, immunohistochemistry, microsatellite instability or mismatch
  repair status, tumor mutational burden, programmed death-ligand 1, hormone
  receptors, human epidermal growth factor receptor 2, and similar predictive,
  prognostic, or diagnostic findings. Biomarkers are NOT routine laboratory
  values and are NOT tumor markers such as carcinoembryonic antigen, CA 19-9,
  CA-125, alpha-fetoprotein, or prostate-specific antigen; tumor markers belong
  under current disease burden when clinically relevant.
- Current and prior treatments, with dates when present. Include details of
  each systemic therapy and local therapy, including surgery and radiation.
- Current and prior adverse events.
- Current and prior comorbidities.
- Current and prior performance status.
- For clinician notes, planned next steps.

STYLE RULES:
- Spell drug names out in full. Expand common oncology shorthand when the
  expansion is clear, for example fluorouracil for 5-FU, oxaliplatin for oxali,
  bevacizumab for bev, pembrolizumab for pembro, capecitabine for cape, and
  doxorubicin, bleomycin, vinblastine, and dacarbazine for ABVD. If expansion
  is uncertain, preserve the documented name and do not guess.
- Preserve dates of current and prior events in the categories above when
  dates are present; partial dates are acceptable.
- Do not invent facts, normalize uncertain values into certainty, or infer a
  biomarker or treatment from cancer type alone.
- Prefer concise clinical prose over exhaustive narrative, but do not omit
  documented biomarkers or distinct treatment lines solely to save words.
"""


def _clean_scalar(value: Any) -> Optional[Any]:
    """Return None for pandas-style missing values or empty strings."""
    if value is None:
        return None
    try:
        if pd.isna(value):
            return None
    except (TypeError, ValueError):
        pass
    text = str(value)
    if text.strip() == "":
        return None
    return value


def append_generated_column(
    frame: pd.DataFrame,
    preferred_name: str,
    values: List[Any],
    existing_cols: set,
) -> str:
    """
    Append a script-generated output column without overwriting an input column.

    Returns the actual column name used. If the preferred name already exists in
    the input, the generated column is written as compression_<name>, with a
    numeric suffix if needed.
    """
    col = preferred_name
    if col in existing_cols:
        base = f"compression_{preferred_name}"
        col = base
        suffix = 2
        while col in existing_cols:
            col = f"{base}_{suffix}"
            suffix += 1
        print(
            f"WARNING: input already has column '{preferred_name}'; "
            f"writing generated values to '{col}'"
        )
    frame[col] = values
    existing_cols.add(col)
    return col


def build_document_user_prompt(
    document_text: str,
    metadata: Dict[str, Any],
) -> str:
    """Build the user message text for one document, with metadata block."""
    metadata_lines = []
    for key, value in metadata.items():
        clean = _clean_scalar(value)
        if clean is not None:
            metadata_lines.append(f"- {key}: {clean}")
    metadata_block = "\n".join(metadata_lines) if metadata_lines else "- none supplied"

    return (
        "Document metadata:\n"
        f"{metadata_block}\n\n"
        "Clinical document:\n"
        "<document>\n"
        f"{document_text}\n"
        "</document>\n"
    )


def build_prompt_text(
    tokenizer,
    document_text: str,
    metadata: Dict[str, Any],
    max_model_len: int,
    margin_tokens: int = 5000,
    model_name: str = "",
) -> str:
    """
    Build a single chat-templated prompt for one clinical document.
    Truncates document text if it is too long for the model context, keeping
    head and tail so first/last sections of the note are preserved.
    """
    threshold = max(1024, max_model_len - margin_tokens)

    toks = tokenizer(document_text, add_special_tokens=False).input_ids
    if len(toks) > threshold:
        half = threshold // 2
        first_part = toks[:half]
        last_part = toks[-half:]
        document_text = tokenizer.decode(first_part) + " ... " + tokenizer.decode(last_part)

    user_content = build_document_user_prompt(document_text, metadata)

    system_content = COMPRESSION_SYSTEM_PROMPT
    if "gpt-oss" in model_name.lower():
        system_content = "Reasoning: high\n\n" + system_content

    messages = [
        {"role": "system", "content": system_content},
        {"role": "user", "content": user_content},
    ]

    prompt = tokenizer.apply_chat_template(
        conversation=messages,
        add_generation_prompt=True,
        tokenize=False,
        enable_thinking=True,
    )
    return prompt


def normalize_summary(text: str) -> str:
    """Strip common wrapper artifacts without changing clinical content."""
    cleaned = text.strip()
    if cleaned.startswith("```"):
        lines = cleaned.splitlines()
        if lines and lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        cleaned = "\n".join(lines).strip()
    lower = cleaned.lower()
    for prefix in ("summary:", "clinical summary:"):
        if lower.startswith(prefix):
            cleaned = cleaned[len(prefix):].strip()
            break
    return cleaned


# Worker functions for parallel prompt building via multiprocessing.Pool.
_worker_tokenizer = None
_worker_model_name = None


def _init_prompt_worker(model_name, download_dir):
    """Initialize tokenizer in each worker process."""
    global _worker_tokenizer, _worker_model_name
    from transformers import AutoTokenizer
    _worker_tokenizer = AutoTokenizer.from_pretrained(
        model_name, cache_dir=download_dir, trust_remote_code=True
    )
    _worker_model_name = model_name


def _build_prompt_worker(item):
    """Build one prompt in a worker. Returns (row_idx, prompt, prompt_token_count)."""
    row_idx, document_text, metadata, max_model_len = item
    prompt = build_prompt_text(
        _worker_tokenizer,
        document_text,
        metadata,
        max_model_len,
        model_name=_worker_model_name,
    )
    prompt_token_count = len(_worker_tokenizer(prompt, add_special_tokens=False).input_ids)
    return (row_idx, prompt, prompt_token_count)


def postprocess_output(raw_text: str, parser_name: str, tokenizer) -> Tuple[str, str]:
    """Split output into (reasoning, summary) via the vLLM reasoning parser."""
    from vllm_reasoning_utils import parse_reasoning_output
    return parse_reasoning_output(raw_text, parser_name, tokenizer)


# -------------------------
# vLLM Server Management
# -------------------------

def start_vllm_server(
    model: str,
    download_dir: str,
    gpu_ids: str,
    tensor_parallel_size: int,
    max_model_len: int,
    gpu_memory_utilization: float,
    reasoning_parser: str,
    max_num_seqs: int = 900,
    port: int = 8000,
    log_file: Optional[str] = None,
    enforce_eager: bool = False,
    additional_vllm_args: Optional[List[str]] = None,
) -> subprocess.Popen:
    """Start vLLM server as a subprocess."""
    env = os.environ.copy()
    env["CUDA_VISIBLE_DEVICES"] = gpu_ids

    cmd = [
        sys.executable, "-m", "vllm.entrypoints.openai.api_server",
        "--model", model,
        "--download-dir", download_dir,
        "--tensor-parallel-size", str(tensor_parallel_size),
        "--max-model-len", str(max_model_len),
        "--max-num-seqs", str(max_num_seqs),
        "--gpu-memory-utilization", str(gpu_memory_utilization),
        "--port", str(port),
        "--reasoning-parser", reasoning_parser,
    ]
    if enforce_eager:
        cmd.append("--enforce-eager")
    if additional_vllm_args:
        cmd.extend(additional_vllm_args)

    print(f"Starting vLLM server: {' '.join(cmd)}")
    print(f"Using GPUs: {gpu_ids}")

    if log_file:
        print(f"vLLM server logs will be written to: {log_file}")
        log_handle = open(log_file, "w")
        process = subprocess.Popen(
            cmd,
            env=env,
            stdout=log_handle,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
        )
        process._log_handle = log_handle
    else:
        print("vLLM server logs will be shown in console")
        process = subprocess.Popen(cmd, env=env)
    return process


def wait_for_server_ready(port: int, timeout: int = 600, poll_interval: float = 5.0) -> bool:
    """Poll health endpoint until server is ready."""
    import time
    health_url = f"http://localhost:{port}/health"
    start_time = time.time()
    print(f"Waiting for vLLM server to be ready at {health_url}...")
    while time.time() - start_time < timeout:
        try:
            response = requests.get(health_url, timeout=5)
            if response.status_code == 200:
                print(f"vLLM server is ready (took {time.time() - start_time:.1f}s)")
                return True
        except requests.exceptions.RequestException:
            pass
        time.sleep(poll_interval)
        elapsed = time.time() - start_time
        print(f"  Still waiting... ({elapsed:.0f}s / {timeout}s)")
    print(f"Timeout waiting for vLLM server after {timeout}s")
    return False


def check_server_health(port: int) -> bool:
    """Check if vLLM server is still responding."""
    try:
        response = requests.get(f"http://localhost:{port}/health", timeout=5)
        return response.status_code == 200
    except requests.exceptions.RequestException:
        return False


def shutdown_server(process: subprocess.Popen, timeout: int = 30):
    """Gracefully terminate the server subprocess."""
    if process is None:
        return
    print("Shutting down vLLM server...")
    if hasattr(process, "_log_handle") and process._log_handle:
        try:
            process._log_handle.close()
        except Exception:
            pass
    process.terminate()
    try:
        process.wait(timeout=timeout)
        print("vLLM server stopped gracefully.")
    except subprocess.TimeoutExpired:
        print("Server did not stop gracefully, forcing kill...")
        process.kill()
        process.wait()
        print("vLLM server killed.")


# -------------------------
# Async Inference
# -------------------------

async def single_inference_request(
    client: AsyncOpenAI,
    row_idx: int,
    prompt: str,
    model: str,
    temperature: float,
    max_tokens: int,
    top_k: int,
    parser_name: str,
    tokenizer,
    top_p: float = 1.0,
    presence_penalty: float = 0.0,
    min_p: float = 0.0,
    repetition_penalty: float = 1.0,
    max_retries: int = 6,
    base_timeout: float = 600.0,
) -> Tuple[int, str, str]:
    """Send a single inference request with retry logic. Returns (row_idx, reasoning, summary)."""
    for attempt in range(max_retries):
        try:
            extra = {
                "top_k": top_k,
                "repetition_penalty": repetition_penalty,
                "skip_special_tokens": False,
            }
            if min_p > 0.0:
                extra["min_p"] = min_p
            response = await asyncio.wait_for(
                client.completions.create(
                    model=model,
                    prompt=prompt,
                    temperature=temperature,
                    max_tokens=max_tokens,
                    top_p=top_p,
                    presence_penalty=presence_penalty,
                    extra_body=extra,
                ),
                timeout=base_timeout,
            )
            raw_text = response.choices[0].text
            reasoning, summary = postprocess_output(raw_text, parser_name, tokenizer)
            summary = normalize_summary(summary)
            return (row_idx, reasoning, summary)

        except asyncio.TimeoutError:
            wait_time = min((2 ** attempt) * 15, 600)
            if attempt < max_retries - 1:
                print(f"  Row {row_idx}: timeout (attempt {attempt + 1}/{max_retries}), retrying in {wait_time}s...")
                await asyncio.sleep(wait_time)
            else:
                print(f"  Row {row_idx}: all retries exhausted (timeout)")
                return (row_idx, "", "ERROR: timeout after all retries")

        except Exception as e:
            wait_time = min((2 ** attempt) * 10, 300)
            if attempt < max_retries - 1:
                print(f"  Row {row_idx}: error '{e}' (attempt {attempt + 1}/{max_retries}), retrying in {wait_time}s...")
                await asyncio.sleep(wait_time)
            else:
                print(f"  Row {row_idx}: all retries exhausted")
                return (row_idx, "", f"ERROR: {e}")

    return (row_idx, "", "ERROR: unexpected retry loop exit")


async def run_inference_on_server(
    client: AsyncOpenAI,
    prompts: List[Tuple[int, str, int]],  # (row_idx, prompt_text, max_tokens)
    model: str,
    temperature: float,
    top_k: int,
    parser_name: str,
    tokenizer,
    top_p: float = 1.0,
    presence_penalty: float = 0.0,
    min_p: float = 0.0,
    repetition_penalty: float = 1.0,
    max_concurrent: int = 16,
    max_retries: int = 6,
    base_timeout: float = 600.0,
    port: int = 8000,
) -> List[Tuple[int, str, str]]:
    """
    Send a list of prompts to one server with bounded concurrency. The caller
    is responsible for splitting work into batches and writing shards; this
    coroutine just blasts the supplied prompts at the server.
    """
    if not prompts:
        return []

    semaphore = asyncio.Semaphore(max_concurrent)

    async def bounded(row_idx: int, prompt: str, prompt_max_tokens: int):
        async with semaphore:
            return await single_inference_request(
                client=client,
                row_idx=row_idx,
                prompt=prompt,
                model=model,
                temperature=temperature,
                max_tokens=prompt_max_tokens,
                top_k=top_k,
                parser_name=parser_name,
                tokenizer=tokenizer,
                top_p=top_p,
                presence_penalty=presence_penalty,
                min_p=min_p,
                repetition_penalty=repetition_penalty,
                max_retries=max_retries,
                base_timeout=base_timeout,
            )

    # Quick health probe before launching the batch
    if not check_server_health(port):
        print(f"  WARNING: server at port {port} health check failed before batch start")

    tasks = [bounded(idx, prompt, mt) for idx, prompt, mt in prompts]
    return await asyncio.gather(*tasks)


# -------------------------
# Sharding (per-row resume)
# -------------------------

_shard_pattern = re.compile(r"compressed_shard_(\d+)\.parquet")


def load_existing_shards(shard_dir: str) -> Dict[int, Tuple[str, str]]:
    """Load all existing shards. Returns dict row_idx -> (reasoning, summary)."""
    results: Dict[int, Tuple[str, str]] = {}
    if not os.path.exists(shard_dir):
        return results
    shard_files = sorted(glob.glob(os.path.join(shard_dir, "compressed_shard_*.parquet")))
    for shard_file in shard_files:
        try:
            shard_df = pd.read_parquet(shard_file)
        except Exception as e:
            print(f"  WARNING: could not read shard {shard_file}: {e}")
            continue
        for _, row in shard_df.iterrows():
            row_idx = int(row["row_idx"])
            reasoning = str(row["reasoning"]) if pd.notna(row["reasoning"]) else ""
            summary = str(row["summary"]) if pd.notna(row["summary"]) else ""
            results[row_idx] = (reasoning, summary)
    return results


def next_shard_index(shard_dir: str) -> int:
    """Return the next shard number to write."""
    if not os.path.exists(shard_dir):
        return 0
    shard_files = glob.glob(os.path.join(shard_dir, "compressed_shard_*.parquet"))
    max_idx = -1
    for path in shard_files:
        m = _shard_pattern.match(os.path.basename(path))
        if m:
            max_idx = max(max_idx, int(m.group(1)))
    return max_idx + 1


def save_shard(
    shard_dir: str,
    shard_idx: int,
    results: List[Tuple[int, str, str]],
) -> str:
    """Save a batch of (row_idx, reasoning, summary) tuples as a shard."""
    os.makedirs(shard_dir, exist_ok=True)
    shard_path = os.path.join(shard_dir, f"compressed_shard_{shard_idx:05d}.parquet")
    shard_df = pd.DataFrame(results, columns=["row_idx", "reasoning", "summary"])
    shard_df.to_parquet(shard_path, index=False)
    print(f"Saved shard: {shard_path} ({len(results)} records)")
    return shard_path


# -------------------------
# Main pipeline
# -------------------------

async def process_all_batches(
    work_rows: List[Tuple[int, str, Dict[str, Any]]],
    args: argparse.Namespace,
    server_clients: List[Tuple[AsyncOpenAI, int]],
    prompt_pool: Pool,
    parser_name: str,
    tokenizer,
    starting_shard_idx: int,
) -> Dict[int, Tuple[str, str]]:
    """
    Run inference on all remaining work_rows in batches, distributing each
    batch round-robin across the configured servers. Saves one shard per batch
    so progress survives crashes.

    work_rows: list of (row_idx, document_text, metadata).
    Returns dict row_idx -> (reasoning, summary) for newly-completed rows.
    """
    n_servers = len(server_clients)
    batch_size = args.batch_size
    new_results: Dict[int, Tuple[str, str]] = {}
    shard_idx = starting_shard_idx

    total = len(work_rows)
    for batch_start in range(0, total, batch_size):
        batch_end = min(batch_start + batch_size, total)
        batch_rows = work_rows[batch_start:batch_end]
        print(f"\n=== Batch {batch_start + 1}-{batch_end} of {total} "
              f"({len(batch_rows)} documents) ===")

        # Build prompts in parallel across CPU cores
        work_items = [
            (row_idx, document_text, metadata, args.max_model_len)
            for row_idx, document_text, metadata in batch_rows
        ]
        print(f"Building {len(work_items)} prompts in parallel...")
        chunksize = max(1, len(work_items) // (prompt_pool._processes * 4))
        prompt_results: List[Tuple[int, str, int]] = list(
            prompt_pool.map(_build_prompt_worker, work_items, chunksize=chunksize)
        )

        # Compute per-prompt max_tokens: leave room for prompt within max_model_len
        prompts: List[Tuple[int, str, int]] = []
        for row_idx, prompt, prompt_token_count in prompt_results:
            gen_tokens = args.max_model_len - prompt_token_count
            if args.max_tokens is not None:
                gen_tokens = min(gen_tokens, args.max_tokens)
            gen_tokens = max(gen_tokens, 1)
            prompts.append((row_idx, prompt, gen_tokens))
        print("Prompts built.")

        # Distribute prompts across servers round-robin
        server_prompt_groups: List[List[Tuple[int, str, int]]] = [[] for _ in range(n_servers)]
        for i, prompt_item in enumerate(prompts):
            server_prompt_groups[i % n_servers].append(prompt_item)

        print(f"Distributing {len(prompts)} requests across {n_servers} server(s)...")
        for si, (_, port) in enumerate(server_clients):
            print(f"  Server {si} (port {port}): {len(server_prompt_groups[si])} prompts")

        # Launch inference on all servers concurrently
        tasks = []
        for server_idx, (client, port) in enumerate(server_clients):
            group = server_prompt_groups[server_idx]
            if group:
                tasks.append(
                    run_inference_on_server(
                        client=client,
                        prompts=group,
                        model=args.model,
                        temperature=args.temperature,
                        top_k=args.top_k,
                        parser_name=parser_name,
                        tokenizer=tokenizer,
                        top_p=args.top_p,
                        presence_penalty=args.presence_penalty,
                        min_p=args.min_p,
                        repetition_penalty=args.repetition_penalty,
                        max_concurrent=args.max_concurrent_requests,
                        max_retries=args.max_retries,
                        base_timeout=args.request_timeout,
                        port=port,
                    )
                )

        all_server_results = await asyncio.gather(*tasks)
        batch_results: List[Tuple[int, str, str]] = []
        for r in all_server_results:
            batch_results.extend(r)

        errors = sum(1 for _, _, s in batch_results if s.startswith("ERROR:"))
        print(f"Batch complete: {len(batch_results)} results ({errors} errors)")

        # Save shard, update state
        save_shard(args.shard_dir, shard_idx, batch_results)
        shard_idx += 1
        for row_idx, reasoning, summary in batch_results:
            new_results[row_idx] = (reasoning, summary)

    return new_results


async def process_all_batches_via_pool(
    work_rows: List[Tuple[int, str, Dict[str, Any]]],
    args: argparse.Namespace,
    prompt_pool: Pool,
    parser_name: str,
    tokenizer,
    starting_shard_idx: int,
) -> Dict[int, Tuple[str, str]]:
    """Remote-pool variant of process_all_batches. Builds prompts via the
    existing multiprocessing pool, then dispatches the entire workload
    through remote_vllm_pool.run_pool — which owns server discovery,
    adaptive concurrency, retry-forever, and persistence."""
    from remote_vllm_pool import (
        CompletionSampling,
        make_completion_work_fn,
        run_pool,
        build_registry_from_args,
    )

    # Build all prompts up-front. Same parallel chunking as
    # process_all_batches but for the whole work_rows.
    print(f"Building {len(work_rows)} prompts in parallel (remote-pool mode)...")
    prompt_inputs = [
        (row_idx, document_text, metadata, args.max_model_len)
        for row_idx, document_text, metadata in work_rows
    ]
    chunksize = max(1, len(prompt_inputs) // (prompt_pool._processes * 4))
    prompt_results: List[Tuple[int, str, int]] = list(
        prompt_pool.map(_build_prompt_worker, prompt_inputs, chunksize=chunksize)
    )

    # Compute per-prompt max_tokens (room for prompt within max_model_len).
    work_items = []
    for row_idx, prompt, prompt_token_count in prompt_results:
        gen_tokens = args.max_model_len - prompt_token_count
        if args.max_tokens is not None:
            gen_tokens = min(gen_tokens, args.max_tokens)
        gen_tokens = max(gen_tokens, 1)
        work_items.append((int(row_idx), {"prompt": prompt, "max_tokens": int(gen_tokens)}))
    print("Prompts built.")

    new_results: Dict[int, Tuple[str, str]] = {}

    def shard_writer(payload, shard_idx):
        rows: List[Tuple[int, str, str]] = []
        for row_idx, result in payload:
            if isinstance(result, str) and result.startswith("ERROR:"):
                reasoning, summary = "", result
            else:
                reasoning, raw_answer = result
                summary = normalize_summary(raw_answer)
            rows.append((row_idx, reasoning, summary))
            new_results[row_idx] = (reasoning, summary)
        save_shard(args.shard_dir, shard_idx, rows)

    sampling = CompletionSampling(
        model=args.model,
        temperature=float(args.temperature),
        top_k=int(args.top_k),
        top_p=float(args.top_p),
        presence_penalty=float(args.presence_penalty),
        min_p=float(args.min_p),
        repetition_penalty=float(args.repetition_penalty),
        request_timeout=float(args.request_timeout),
    )
    work_fn = make_completion_work_fn(sampling, parser_name, tokenizer)

    # Allow --max_concurrent_per_server to override the older
    # --max_concurrent_requests when set explicitly.
    if args.max_concurrent_per_server is None:
        args.max_concurrent_per_server = int(args.max_concurrent_requests)
    registry = build_registry_from_args(args)

    await run_pool(
        work_items=work_items,
        work_fn=work_fn,
        registry=registry,
        shard_writer=shard_writer,
        results_per_shard=int(args.batch_size),
        starting_shard_idx=starting_shard_idx,
        max_attempts=int(args.max_attempts),
    )
    await registry.stop()
    return new_results


def main():
    ap = argparse.ArgumentParser(
        "Per-document clinical note compression using vLLM server(s)."
    )
    ap.add_argument("--input_parquet", help="Input parquet file (one document per row).")
    ap.add_argument("--input_csv", help="Input CSV/TSV file (one document per row). Alternative to --input_parquet.")
    ap.add_argument("--output_parquet", required=True, help="Output parquet with per-document summaries.")
    ap.add_argument("--output_csv", default=None, help="Optional CSV mirror of the output parquet.")
    ap.add_argument("--shard_dir", required=True, help="Directory for checkpoint shards (used for resume).")

    ap.add_argument("--patient_id_col", default="pseudo_mrn", help="Column name for patient ID (optional metadata).")
    ap.add_argument("--date_col", default="date", help="Column name for note date (optional metadata; safe if missing).")
    ap.add_argument("--note_type_col", default="note_type", help="Column name for note type (optional metadata; safe if missing).")
    ap.add_argument("--document_id_col", default=None, help="Optional column name for document ID. Defaults to row index.")
    ap.add_argument("--text_col", default="synthetic_note", help="Column name for note text.")

    ap.add_argument("--model", default="gpt-oss-120b")
    ap.add_argument("--download_dir", required=True)
    ap.add_argument("--gpu_ids", default=None,
                    help="Comma-separated GPU IDs (e.g., 0,1,2,3). Required unless --server_urls is set.")
    ap.add_argument("--gpus_per_server", type=int, default=None,
                    help="Number of GPUs per vLLM server. n_servers = len(gpu_ids) // gpus_per_server. "
                         "tensor_parallel_size is set to this value. Required unless --server_urls is set.")
    ap.add_argument("--max_model_len", type=int, default=25000)
    ap.add_argument("--enforce_eager", action="store_true",
                    help="Pass --enforce-eager to vLLM (disables CUDA graphs).")
    ap.add_argument("--additional_vllm_args", type=str, default="",
                    help="Extra arguments to append verbatim to the vLLM server command "
                         "(shell-quoted). Ignored when --server_urls is set.")
    ap.add_argument("--max_num_seqs", type=int, default=900, help="vLLM max_num_seqs.")

    ap.add_argument("--temperature", type=float, default=0.0)
    ap.add_argument("--top_k", type=int, default=1)
    ap.add_argument("--top_p", type=float, default=1.0)
    ap.add_argument("--presence_penalty", type=float, default=0.0)
    ap.add_argument("--min_p", type=float, default=0.0)
    ap.add_argument("--max_tokens", type=int, default=1024,
                    help="Max generation tokens per document summary.")
    ap.add_argument("--repetition_penalty", type=float, default=1.1)

    from vllm_reasoning_utils import add_reasoning_cli_args
    add_reasoning_cli_args(ap)

    ap.add_argument("--gpu_memory_utilization", type=float, default=0.90)
    ap.add_argument("--base_port", type=int, default=8000,
                    help="Base port for vLLM servers (server i uses base_port + i).")
    ap.add_argument("--server_urls", type=str, default=None,
                    help="Comma-separated URLs of existing vLLM servers "
                         "(e.g. 'http://localhost:8000/v1,http://localhost:8001/v1'). "
                         "When set, no servers are started or stopped.")
    ap.add_argument("--server_urls_file", type=str, default=None,
                    help="Path to JSON file maintained by gcp_vllm_orchestrator.py "
                         "with the dynamic list of healthy server URLs. Mutually "
                         "exclusive with --server_urls.")
    ap.add_argument("--server_urls_refresh", type=float, default=15.0,
                    help="Seconds between re-reads of --server_urls_file.")
    ap.add_argument("--max_concurrent_per_server", type=int, default=None,
                    help="Per-server concurrency ceiling for remote-pool mode "
                         "(adaptive; backs off on errors). Defaults to "
                         "--max_concurrent_requests if not set.")
    ap.add_argument("--max_attempts", type=int, default=200,
                    help="Per-item max retries before recording an ERROR placeholder. "
                         "Default 200 (effectively 'retry until done').")

    ap.add_argument("--max_concurrent_requests", type=int, default=25,
                    help="Maximum concurrent requests per server.")
    ap.add_argument("--batch_size", type=int, default=1000,
                    help="Documents per batch (one shard is written per batch).")
    ap.add_argument("--request_timeout", type=float, default=600.0,
                    help="Per-request timeout in seconds.")
    ap.add_argument("--max_retries", type=int, default=6,
                    help="Maximum retries for failed requests.")
    ap.add_argument("--server_timeout", type=int, default=600,
                    help="Timeout in seconds waiting for vLLM server to start.")
    ap.add_argument("--max_docs", type=int, default=None,
                    help="Limit to first N documents (for testing).")

    args = ap.parse_args()

    if not args.input_parquet and not args.input_csv:
        ap.error("One of --input_parquet or --input_csv is required.")
    if args.input_parquet and args.input_csv:
        ap.error("Specify only one of --input_parquet / --input_csv.")
    if args.server_urls and args.server_urls_file:
        ap.error("Specify only one of --server_urls / --server_urls_file.")
    remote_mode = bool(args.server_urls or args.server_urls_file)
    if not remote_mode and (not args.gpu_ids or args.gpus_per_server is None):
        ap.error("--gpu_ids and --gpus_per_server are required unless --server_urls / --server_urls_file is set.")

    # Resolve reasoning parser from --model + --reasoning-parser (default auto)
    from vllm_reasoning_utils import resolve_parser_name
    reasoning_parser = resolve_parser_name(args.model, args.reasoning_parser)
    print(f"Using vLLM reasoning parser: {reasoning_parser}")

    # Load tokenizer (used for parsing reasoning output)
    print("Loading tokenizer...")
    from transformers import AutoTokenizer
    tokenizer = AutoTokenizer.from_pretrained(
        args.model, cache_dir=args.download_dir, trust_remote_code=True
    )

    # ---- Load input ----
    if args.input_parquet:
        input_path = args.input_parquet
        print(f"Loading {input_path}...")
        df = pd.read_parquet(input_path)
    else:
        input_path = args.input_csv
        print(f"Loading {input_path}...")
        sep = "\t" if input_path.lower().endswith(".tsv") else ","
        df = pd.read_csv(input_path, sep=sep, low_memory=False)

    if args.text_col not in df.columns:
        raise ValueError(
            f"Column '{args.text_col}' (--text_col) not found in input. "
            f"Available columns: {df.columns.tolist()}"
        )

    if args.max_docs is not None:
        df = df.head(args.max_docs).copy()
        print(f"Limited to first {args.max_docs} documents")

    df = df.reset_index(drop=True)
    input_df_for_output = df.copy()
    df["row_idx"] = df.index.astype(int)
    total_docs = len(df)
    print(f"Loaded {total_docs} documents")

    # ---- Resume from shards ----
    os.makedirs(args.shard_dir, exist_ok=True)
    existing_results = load_existing_shards(args.shard_dir)
    if existing_results:
        print(f"Resuming: {len(existing_results)} documents already compressed in shards")

    # Build work list of (row_idx, document_text, metadata) for not-yet-done rows
    has_patient = args.patient_id_col in df.columns
    has_date = args.date_col in df.columns
    has_note_type = args.note_type_col in df.columns
    has_doc_id = args.document_id_col is not None and args.document_id_col in df.columns

    work_rows: List[Tuple[int, str, Dict[str, Any]]] = []
    skipped_empty = 0
    for row in df.itertuples(index=False):
        row_idx = int(getattr(row, "row_idx"))
        if row_idx in existing_results:
            continue
        text_value = _clean_scalar(getattr(row, args.text_col, None))
        text = "" if text_value is None else str(text_value)
        if not text.strip():
            # Mark empty rows immediately as completed (no inference needed)
            existing_results[row_idx] = ("", "")
            skipped_empty += 1
            continue
        metadata: Dict[str, Any] = {}
        if has_doc_id:
            metadata["document_id"] = _clean_scalar(getattr(row, args.document_id_col, None))
        else:
            metadata["document_id"] = f"row{row_idx}"
        if has_patient:
            metadata["patient_id"] = _clean_scalar(getattr(row, args.patient_id_col, None))
        if has_date:
            metadata["date"] = _clean_scalar(getattr(row, args.date_col, None))
        if has_note_type:
            metadata["note_type"] = _clean_scalar(getattr(row, args.note_type_col, None))
        work_rows.append((row_idx, text, metadata))

    print(f"To compress: {len(work_rows)} documents "
          f"({len(existing_results) - skipped_empty} already done, {skipped_empty} empty/skipped)")

    # ---- Server setup ----
    server_infos: List[Tuple[subprocess.Popen, int]] = []
    server_clients: List[Tuple[AsyncOpenAI, int]] = []

    if work_rows and not remote_mode:
        if args.server_urls:
            # Legacy static --server_urls path (no dynamic registry)
            urls = [u.strip() for u in args.server_urls.split(",") if u.strip()]
            print(f"Using {len(urls)} external server(s): {urls}")
            for url in urls:
                from urllib.parse import urlparse
                parsed = urlparse(url)
                port = parsed.port or 0
                client = AsyncOpenAI(
                    base_url=url,
                    api_key="not-needed",
                    timeout=args.request_timeout + 60,
                )
                server_clients.append((client, port))
            print(f"All {len(server_clients)} external server(s) connected.")
        else:
            gpu_ids_normalized = args.gpu_ids.replace(";", ",")
            gpu_list = [g.strip() for g in gpu_ids_normalized.split(",") if g.strip()]

            if len(gpu_list) % args.gpus_per_server != 0:
                remainder = len(gpu_list) % args.gpus_per_server
                usable = len(gpu_list) - remainder
                print(f"WARNING: {len(gpu_list)} GPUs not evenly divisible by "
                      f"gpus_per_server={args.gpus_per_server}. "
                      f"Using first {usable} GPUs, ignoring: {gpu_list[usable:]}")
                gpu_list = gpu_list[:usable]

            n_servers = len(gpu_list) // args.gpus_per_server
            if n_servers == 0:
                raise ValueError(
                    f"Not enough GPUs ({len(gpu_list)}) for gpus_per_server={args.gpus_per_server}"
                )

            print(f"Starting {n_servers} vLLM server(s), each with {args.gpus_per_server} GPU(s)")

            extra_vllm_args = shlex.split(args.additional_vllm_args) if args.additional_vllm_args else []
            if extra_vllm_args:
                print(f"Appending additional vLLM args: {extra_vllm_args}")

            for server_idx in range(n_servers):
                gpu_start = server_idx * args.gpus_per_server
                gpu_end = gpu_start + args.gpus_per_server
                server_gpu_ids = ",".join(gpu_list[gpu_start:gpu_end])
                server_port = args.base_port + server_idx
                log_file = os.path.join(args.shard_dir, f"vllm_server_{server_idx}.log")
                process = start_vllm_server(
                    model=args.model,
                    download_dir=args.download_dir,
                    gpu_ids=server_gpu_ids,
                    tensor_parallel_size=args.gpus_per_server,
                    max_model_len=args.max_model_len,
                    gpu_memory_utilization=args.gpu_memory_utilization,
                    reasoning_parser=reasoning_parser,
                    max_num_seqs=args.max_num_seqs,
                    port=server_port,
                    log_file=log_file,
                    enforce_eager=args.enforce_eager,
                    additional_vllm_args=extra_vllm_args,
                )
                server_infos.append((process, server_port))

            for i, (process, port) in enumerate(server_infos):
                print(f"Waiting for server {i} (port {port})...")
                if not wait_for_server_ready(port, timeout=args.server_timeout):
                    print(f"Failed to start vLLM server {i} on port {port}. Shutting down all servers.")
                    for proc, _ in server_infos:
                        shutdown_server(proc)
                    sys.exit(1)

            for i, (process, port) in enumerate(server_infos):
                client = AsyncOpenAI(
                    base_url=f"http://localhost:{port}/v1",
                    api_key="not-needed",
                    timeout=args.request_timeout + 60,
                )
                server_clients.append((client, port))
            print(f"All {len(server_clients)} vLLM server(s) ready.")

    # ---- Prompt-building pool + inference ----
    if work_rows:
        n_workers = min(os.cpu_count() or 4, 32)
        print(f"Creating prompt-building pool with {n_workers} workers...")
        prompt_pool = Pool(
            processes=n_workers,
            initializer=_init_prompt_worker,
            initargs=(args.model, args.download_dir),
        )

        try:
            starting_shard_idx = next_shard_index(args.shard_dir)
            if remote_mode:
                new_results = asyncio.run(
                    process_all_batches_via_pool(
                        work_rows=work_rows,
                        args=args,
                        prompt_pool=prompt_pool,
                        parser_name=reasoning_parser,
                        tokenizer=tokenizer,
                        starting_shard_idx=starting_shard_idx,
                    )
                )
            else:
                new_results = asyncio.run(
                    process_all_batches(
                        work_rows=work_rows,
                        args=args,
                        server_clients=server_clients,
                        prompt_pool=prompt_pool,
                        parser_name=reasoning_parser,
                        tokenizer=tokenizer,
                        starting_shard_idx=starting_shard_idx,
                    )
                )
            existing_results.update(new_results)
        finally:
            prompt_pool.close()
            prompt_pool.join()
            if server_infos:
                print(f"Shutting down {len(server_infos)} vLLM server(s)...")
                for i, (process, port) in enumerate(server_infos):
                    print(f"  Shutting down server {i} (port {port})...")
                    shutdown_server(process)
                print("All servers shut down.")
            elif remote_mode:
                print("Remote vLLM servers (managed by orchestrator) left running.")
            else:
                print("External servers left running (not managed by this script).")
    else:
        print("Nothing to compress; all rows already done.")

    # ---- Assemble final output ----
    from datetime import date
    summary_generation_date = date.today().isoformat()

    print("\nBuilding final output...")

    # One-off merge for older compressed outputs that did not carry the input
    # columns. This is not needed for new outputs from this version.
    #
    # notes = pd.read_parquet("../data/no_phi/all_synthetic_notes.parquet").reset_index(drop=True)
    # notes["row_idx"] = notes.index.astype(int)
    # compressed = pd.read_parquet("../data/no_phi/compressed_synthetic_notes.parquet")
    # merged = compressed.merge(notes, on="row_idx", how="left", suffixes=("", "_original"))
    # merged.to_parquet("../data/no_phi/compressed_synthetic_notes_with_original_notes.parquet", index=False)

    include_generated_document_id = "document_id" not in input_df_for_output.columns
    generated_values: Dict[str, List[Any]] = {"row_idx": []}
    if include_generated_document_id:
        generated_values["document_id"] = []
    generated_values.update({
        "text_chars": [],
        "summary": [],
        "summary_reasoning": [],
        "summary_generation_date": [],
    })

    for row in df.itertuples(index=False):
        row_idx = int(getattr(row, "row_idx"))
        reasoning, summary = existing_results.get(row_idx, ("", ""))
        text_value = _clean_scalar(getattr(row, args.text_col, None))
        text = "" if text_value is None else str(text_value)
        document_id = (
            _clean_scalar(getattr(row, args.document_id_col, None))
            if has_doc_id else f"row{row_idx}"
        )

        generated_values["row_idx"].append(row_idx)
        if include_generated_document_id:
            generated_values["document_id"].append(document_id)
        generated_values["text_chars"].append(len(text))
        generated_values["summary"].append(summary)
        generated_values["summary_reasoning"].append(reasoning)
        generated_values["summary_generation_date"].append(summary_generation_date)

    out_df = input_df_for_output.copy()
    existing_cols = set(out_df.columns)
    generated_col_names: Dict[str, str] = {}
    for preferred_name, values in generated_values.items():
        generated_col_names[preferred_name] = append_generated_column(
            out_df, preferred_name, values, existing_cols
        )

    # Coerce nullable generated string columns for parquet stability.
    for preferred_name in ("document_id", "summary", "summary_reasoning", "summary_generation_date"):
        col = generated_col_names.get(preferred_name)
        if col is not None:
            out_df[col] = out_df[col].astype("object").where(out_df[col].notna(), None)
            out_df[col] = out_df[col].apply(lambda v: None if v is None else str(v))

    out_df.to_parquet(args.output_parquet, index=False)
    print(f"Wrote {args.output_parquet} with {len(out_df)} rows.")

    if args.output_csv:
        out_df.to_csv(args.output_csv, index=False)
        print(f"Wrote {args.output_csv}.")

    summary_col = generated_col_names["summary"]
    error_count = int(out_df[summary_col].astype(str).str.startswith("ERROR:").sum())
    empty_count = int((out_df[summary_col].astype(str).str.strip() == "").sum())
    print(f"Summary: {len(out_df)} documents | "
          f"{error_count} errors | {empty_count} empty/skipped summaries")


if __name__ == "__main__":
    warnings.filterwarnings("ignore")
    main()
